************* Module python_scripts.timezone_utils
python_scripts/timezone_utils.py:1:0: C0114: Missing module docstring (missing-module-docstring)
python_scripts/timezone_utils.py:8:0: C0103: Function name "userTimeZone" doesn't conform to snake_case naming style (invalid-name)
python_scripts/timezone_utils.py:31:0: C0103: Function name "currentTime" doesn't conform to snake_case naming style (invalid-name)
python_scripts/timezone_utils.py:39:0: C0103: Function name "convertTime" doesn't conform to snake_case naming style (invalid-name)
python_scripts/timezone_utils.py:52:0: C0116: Missing function or method docstring (missing-function-docstring)
python_scripts/timezone_utils.py:52:0: C0103: Function name "calendarTimeZone" doesn't conform to snake_case naming style (invalid-name)
************* Module python_scripts.auth
python_scripts/auth.py:43:0: C0301: Line too long (108/100) (line-too-long)
python_scripts/auth.py:54:0: C0303: Trailing whitespace (trailing-whitespace)
python_scripts/auth.py:69:0: C0304: Final newline missing (missing-final-newline)
python_scripts/auth.py:1:0: C0114: Missing module docstring (missing-module-docstring)
python_scripts/auth.py:8:0: C0116: Missing function or method docstring (missing-function-docstring)
python_scripts/auth.py:10:4: C0103: Variable name "CLIENT_ID" doesn't conform to snake_case naming style (invalid-name)
python_scripts/auth.py:11:4: C0103: Variable name "CLIENT_SECRET" doesn't conform to snake_case naming style (invalid-name)
python_scripts/auth.py:19:4: C0103: Variable name "SCOPES" doesn't conform to snake_case naming style (invalid-name)
python_scripts/auth.py:20:4: C0103: Variable name "ENVIRONMENT" doesn't conform to snake_case naming style (invalid-name)
python_scripts/auth.py:36:16: C0103: Variable name "REDIRECT_URI" doesn't conform to snake_case naming style (invalid-name)
python_scripts/auth.py:56:21: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
************* Module python_scripts.manage_events
python_scripts/manage_events.py:71:0: C0304: Final newline missing (missing-final-newline)
python_scripts/manage_events.py:1:0: C0114: Missing module docstring (missing-module-docstring)
python_scripts/manage_events.py:12:5: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
python_scripts/manage_events.py:21:0: C0103: Function name "createEvent" doesn't conform to snake_case naming style (invalid-name)
python_scripts/manage_events.py:21:0: R0913: Too many arguments (6/5) (too-many-arguments)
python_scripts/manage_events.py:37:4: C0103: Variable name "localTimeZone" doesn't conform to snake_case naming style (invalid-name)
python_scripts/manage_events.py:68:12: E1101: Instance of 'Resource' has no 'events' member (no-member)
************* Module python_scripts.auth_manage_events
python_scripts/auth_manage_events.py:6:0: C0303: Trailing whitespace (trailing-whitespace)
python_scripts/auth_manage_events.py:12:0: C0303: Trailing whitespace (trailing-whitespace)
python_scripts/auth_manage_events.py:18:0: C0304: Final newline missing (missing-final-newline)
python_scripts/auth_manage_events.py:1:0: C0114: Missing module docstring (missing-module-docstring)
python_scripts/auth_manage_events.py:4:0: C0116: Missing function or method docstring (missing-function-docstring)
python_scripts/auth_manage_events.py:5:24: W1510: 'subprocess.run' used without explicitly defining the value for 'check'. (subprocess-run-check)
python_scripts/auth_manage_events.py:9:8: W0719: Raising too general exception: Exception (broad-exception-raised)
************* Module python_scripts.auth_get_events
python_scripts/auth_get_events.py:6:0: C0303: Trailing whitespace (trailing-whitespace)
python_scripts/auth_get_events.py:12:0: C0303: Trailing whitespace (trailing-whitespace)
python_scripts/auth_get_events.py:18:0: C0304: Final newline missing (missing-final-newline)
python_scripts/auth_get_events.py:1:0: C0114: Missing module docstring (missing-module-docstring)
python_scripts/auth_get_events.py:4:0: C0116: Missing function or method docstring (missing-function-docstring)
python_scripts/auth_get_events.py:5:24: W1510: 'subprocess.run' used without explicitly defining the value for 'check'. (subprocess-run-check)
python_scripts/auth_get_events.py:9:8: W0719: Raising too general exception: Exception (broad-exception-raised)
************* Module python_scripts.get_events
python_scripts/get_events.py:10:0: C0303: Trailing whitespace (trailing-whitespace)
python_scripts/get_events.py:33:0: C0301: Line too long (138/100) (line-too-long)
python_scripts/get_events.py:34:0: C0301: Line too long (115/100) (line-too-long)
python_scripts/get_events.py:40:0: C0304: Final newline missing (missing-final-newline)
python_scripts/get_events.py:1:0: C0114: Missing module docstring (missing-module-docstring)
python_scripts/get_events.py:8:5: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
python_scripts/get_events.py:16:0: C0103: Function name "upcomingEvents" doesn't conform to snake_case naming style (invalid-name)
python_scripts/get_events.py:16:28: C0103: Argument name "CLIENT_CITY" doesn't conform to snake_case naming style (invalid-name)
python_scripts/get_events.py:16:19: W0621: Redefining name 'service' from outer scope (line 12) (redefined-outer-name)
python_scripts/get_events.py:26:4: W0621: Redefining name 'events' from outer scope (line 39) (redefined-outer-name)
python_scripts/get_events.py:20:4: C0103: Variable name "localTimeZone" doesn't conform to snake_case naming style (invalid-name)
python_scripts/get_events.py:1:0: R0801: Similar lines in 2 files
==python_scripts.auth_get_events:[4:16]
==python_scripts.auth_manage_events:[4:16]
    completed_process = subprocess.run(['python3', script_path], text=True, capture_output=True)

    # Check if the script ran successfully
    if completed_process.returncode != 0:
        raise Exception(f"Script {script_path} encountered an error: {completed_process.stderr}")

    return completed_process.stdout.strip()  # Return the script output

# run_script('auth.py')
# run_script('get_events.py')

run_script('./python_scripts/auth.py') (duplicate-code)
python_scripts/get_events.py:1:0: R0801: Similar lines in 2 files
==python_scripts.get_events:[10:20]
==python_scripts.manage_events:[14:37]
try:
    service = build('calendar', 'v3', credentials=creds)
except HttpError as error:
    print("An error occurred: ", error)

# Reference: https://developers.google.com/calendar/api/guides/create-events
def createEvent(summary: Optional[str] = None, \
                description: Optional[str] = None, \
                location: Optional[str] = None, \
                start_datetime: Optional[Union[str, datetime.datetime]] = None, \
                end_datetime: Optional[Union[str, datetime.datetime]] = None, \
                attendees: Optional[List[str]] = None) -> str:
    """
    Create an event on a user's calendar.
    Args:
        summary (Optional[str]): The title / summary for the event
        description (Optional[str]): The description for the event
        location (Optional[str]): The location for the event
        start_datetime Optional[Union[str, datetime.datetime]]: The start datetime for the event
        end_datetime Optional[Union[str, datetime.datetime]]: The end datetime for the event
        attendees Optional[List[str]]: A list of email address to invite to the event
    """
    localTimeZone = userTimeZone(CLIENT_CITY) (duplicate-code)

------------------------------------------------------------------
Your code has been rated at 5.86/10 (previous run: 5.79/10, +0.08)

